package by.epam.cafe.command;



public enum CommandType {
    LOGIN ,
    LOGOUT,
    SIGNUP,
    SHOWDISH,
    LOCALE,
    ADDTOBASKET,
    REMOVEFROMBASKET,
    MAKEORDER,
    SHOWMYORDER,
    FINDUSERBYSURNAME,
    SHOWORDERS,
    PAYADMIN,
    DELIVER,
    SHOWORDERBYDATE,
    SORTORDERMAP,
    EDITUSER,
    SENDPASS,
    CHANGEPASS,
    ADDKITCHEN,
    ADDDISH,
    ADDCATEGORY,
    UPDATEARCHIVESTATUS,
    SHOWCATEGORY,
    SHOWKITCHEN,
    UPDATELOYALTYPOINT,
    UPDATEKITCHEN,
    REFUSETHEORDER
}
